---
- name: Install vagrant-libvirt dependencies
  apt:
    update_cache: "yes"
    state: present
    name:
      - bridge-utils
      - ca-certificates
      - curl
      - gcc
      - libxslt-dev
      - libxml2-dev
      - libvirt0
      - libvirt-dev
      - make
      - pkg-config
      - qemu-kvm
      - ssh
      - zlib1g-dev
      - ruby-dev
      - kmod

- name: Ensure temp download directory exist
  file: state=directory path={{vagrant_tmp_dir}}
  tags: ["packages","vagrant"]

- name: Download Vagrant
  get_url:
    url: "{{ vagrant_url_deb }}"
    dest: "{{ vagrant_tmp_deb }}"

- name: Install vagrant for debian
  apt:
    deb: "{{vagrant_tmp_deb}}/vagrant_{{ vagrant_version }}_x86_64.deb"
